### ISSUE TITLE
[question] non-ansi features

### ISSUE THREAD

**Issue by dkochmanski** [didierverna/clon#1]
1. When I have commented out check for `CC` variable in `setup/setup.lisp` for SBCL everything seems to work just fine even if `CC` is not set (i.e colors). Do I miss something?
2. As far as I understand, `termio` can be configured with `cffi-grovel` - why is this restricted in `termio/net.didierverna.clon.termio.asd` only to `allegro`, `clisp` and `lispworks` – shouldn't it be `cffi-grovel` responsibility to verify if implementation is supported?
3. Can SBCL use `cffi-grovel` like other implementations or it uses `sb-grovel` module for a reason beyond keeping dependencies minimal?

Thanks for CLON, I find it very useful (and it has a great documentation, what is a very rare thing).

**Comment by didierverna** [comment]
Hi,

relevant parts of the documentation are section 2 (Installation) and
A.1-3 (Appendix).

Daniel Kochmanski notifications@github.com wrote:

> 1 When I have commented out check for CC variable in setup/setup.lisp
> for SBCL everything seems to work just fine even if CC is not set. Do
> I miss something?

  It is likely that without a properly set CC variable, Clon will be
  compiled in restricted mode and you will lack colorized
  output. Another possibility is that recent SBCL removed the need for
  an explicitly set CC variable for the grovel part, but I haven't
  checked that yet.

> 2 As far as I understand, termio can be configured with cffi-grovel -
> why is this strictly restricted in
> termio/net.didierverna.clon.termio.asd only to allegro, clisp and
> lispworks – shouldn't it be cffi-grovel responsibility to verify such
> dependency?

  That's because Clon prefers to use a native ffi when available (or at
  least that I know of). So SBCL will use sb-grovel, and the other guys
  will use CFFI. It is thus my (termio) responsibility to choose.

> 3 Can SBCL use cffi-grovel like other implementations or it uses
> sb-grovel moudle for a reason beyond keeping dependencies minimal?

  No, the only reason is to keep dependencies minimal. SBCL could use
  cffi-grovel.

> Thanks for CLON, I find it very useful (and it has a great
> documentation, what is a very rare thing).

  Yup, I actually like writing documentation. It's a feedback loop (it
  helps writing better code).

## 

Resistance is futile. You will be jazzimilated.

Lisp, Jazz, Aïkido: http://www.didierverna.info

**Comment by dkochmanski** [comment]
Thanks, all clear now.
